<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>Gm1KonverterCrossPlatform.Core</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591;CS1573;NETSDK1138</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.13" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Gm1KonverterCrossPlatform.Tests" />
  </ItemGroup>
</Project>
